# Generated by Django 3.0.4 on 2020-05-06 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0002_auto_20200505_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='mask_Main_Img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='link_number',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='materials_text',
            new_name='materials',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='title_text',
            new_name='title',
        ),
    ]
