# Generated by Django 3.0.4 on 2020-05-07 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0004_auto_20200507_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='name',
        ),
        migrations.AddField(
            model_name='title',
            name='update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
