# Generated by Django 3.0.4 on 2020-05-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0010_auto_20200508_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='show_link',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
