# Generated by Django 3.0.4 on 2020-05-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0011_auto_20200508_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='show_link',
        ),
    ]
