# Generated by Django 3.0.4 on 2020-05-08 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0015_auto_20200508_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='show_url',
            new_name='show_link',
        ),
    ]
