# Generated by Django 3.0.4 on 2020-05-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0017_title_show_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='show_url',
        ),
    ]
