# Generated by Django 3.0.4 on 2020-05-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0018_remove_title_show_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='show_link',
        ),
    ]
