# Generated by Django 3.0.4 on 2020-05-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0019_remove_title_show_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='resource',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
