# Generated by Django 3.0.4 on 2020-05-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0022_auto_20200509_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='level',
            field=models.CharField(default=None, max_length=8, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='title',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
