# Generated by Django 3.0.4 on 2020-05-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0023_auto_20200509_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='level',
            field=models.CharField(blank=True, max_length=8, verbose_name='Level'),
        ),
    ]
