# Generated by Django 3.0.4 on 2020-05-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0027_auto_20200509_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='level',
            field=models.CharField(default='Easy', max_length=8, verbose_name='Level'),
        ),
    ]
