# Generated by Django 3.0.4 on 2020-05-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0004_auto_20200509_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Ok', 'Ok'), ('Hard', 'Hard')], default='Easy', max_length=6),
        ),
    ]
