# Generated by Django 3.0.4 on 2020-05-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0005_auto_20200509_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='image',
            field=models.ImageField(default='images/noimage.gif', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='title',
            name='level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('OK', 'OK'), ('Hard', 'Hard')], default='Easy', max_length=6),
        ),
    ]
