# Generated by Django 3.0.4 on 2020-05-05 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials_text', models.CharField(max_length=800)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masks.Title')),
            ],
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mask_Main_Img', models.ImageField(upload_to='images/')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masks.Title')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_number', models.URLField(blank=True, db_index=True, max_length=150, unique=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masks.Title')),
            ],
        ),
    ]
