# Generated by Django 3.0.4 on 2020-05-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mask',
            name='title',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='title',
        ),
        migrations.AddField(
            model_name='title',
            name='link_number',
            field=models.URLField(blank=True, db_index=True, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='title',
            name='mask_Main_Img',
            field=models.ImageField(default='images/noimage.gif', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='title',
            name='materials_text',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Mask',
        ),
        migrations.DeleteModel(
            name='Materials',
        ),
    ]
