# Generated by Django 3.0.4 on 2020-05-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0003_auto_20200505_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='link',
            new_name='show_url',
        ),
        migrations.AlterField(
            model_name='title',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
