# Generated by Django 3.0.4 on 2020-05-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0005_auto_20200507_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='show_url',
        ),
        migrations.AddField(
            model_name='title',
            name='show_link',
            field=models.CharField(blank=True, db_index=True, max_length=150, unique=True),
        ),
    ]
