# Generated by Django 3.0.4 on 2020-05-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0007_auto_20200508_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='show_link',
        ),
    ]
