# Generated by Django 3.0.4 on 2020-05-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0008_remove_title_show_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='show_link',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
