# Generated by Django 3.0.4 on 2020-05-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0013_title_show_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='show_link',
            new_name='show_url',
        ),
    ]
