# Generated by Django 3.0.4 on 2020-05-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0014_auto_20200508_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='show_url',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
