# Generated by Django 3.0.4 on 2020-05-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0020_title_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='resource',
            field=models.URLField(blank=True, max_length=150),
        ),
    ]
